version: '3'
services:
  mariadb:
    image: mariadb:10
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: geheim
      MYSQL_DATABASE: sandbox_local
      MYSQL_USER: user
      MYSQL_PASSWORD: geheim
    networks:
      - mysql

networks:
  mysql:
    external: true
